intf_libs = # Interface dependencies.
impl_libs = # Implementation dependencies.
#import xxxx_libs += libhello%lib{hello}

lib{b2}: {h c}{**} $impl_libs $intf_libs

h{export}@./: c.importable = false

# Build options.
#
c.poptions =+ "-I$out_root" "-I$src_root"

{hbmia obja}{*}: c.poptions += -DSRC_STATIC_BUILD
{hbmis objs}{*}: c.poptions += -DSRC_SHARED_BUILD

# Export options.
#
lib{b2}:
{
  c.export.poptions = "-I$out_root" "-I$src_root"
  c.export.libs = $intf_libs
}

liba{b2}: c.export.poptions += -DSRC_STATIC
libs{b2}: c.export.poptions += -DSRC_SHARED

# For pre-releases use the complete version to make sure they cannot be used
# in place of another pre-release or the final version. See the version module
# for details on the version.* variable values.
#
if $version.pre_release
  lib{b2}: bin.lib.version = "-$version.project_id"
else
  lib{b2}: bin.lib.version = "-$version.major.$version.minor"

# Install into the src/ subdirectory of, say, /usr/include/
# recreating subdirectories.
#
h{*}:
{
  install         = include/src/
  install.subdirs = true
}
